/**
 * RootLayout - Configurator V2 Component
 *
 * Component RootLayout from layout.tsx
 *
 * @migrated from DAISY v1
 */

import "reflect-metadata";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { headers } from "next/headers";
import Script from "next/script";

import "./globals.css";
import { ProfileProvider } from "@presentation/components/profileContext/ProfileContext";
import { TanStackProviders } from "./tanstack-provider";
import { MSALProvider } from "./(presentation)/components/auth/MSALAuthProvider";
import 'mapbox-gl/dist/mapbox-gl.css';
import { Toaster } from "@/components/ui/sonner";
import ClarityProvider from './clarityProvider';
import SystemAlertBanner from "./(presentation)/components/SystemAlertBanner";
import FormBricks from './formBricks';

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DAISY",
  description: "Generated by create next app",
};

  /**
   * BUSINESS LOGIC: RootLayout
   *
   * WHY THIS EXISTS:
   * - Implements business logic requirement
   *
   * WHAT IT DOES:
   * 1. Implements RootLayout logic
   * 2. Calls helper functions: headers, allHeaders.get
   * 3. Returns computed result
   *
   * WHAT IT CALLS:
   * - headers() - Function call
   * - allHeaders.get() - Function call
   *
   * WHY IT CALLS THEM:
   * - headers: Required functionality
   * - allHeaders.get: Required functionality
   *
   * DATA FLOW:
   * Input: Component state and props
   * Processing: Calls headers, allHeaders.get to process data
   * Output: Computed value or side effect
   *
   */
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const allHeaders = await headers();
  const nonce = allHeaders.get("x-nonce") ?? "";

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/images/daisy.png" sizes="any" />
        <Script id="init" nonce={nonce} strategy="afterInteractive">
          {`console.log("Nonce is attached securely!")`}
        </Script>
      </head>
      <body className={`${geistSans.variable} antialiased`}>
        <ClarityProvider />
        <FormBricks />
        <MSALProvider>
          <ProfileProvider>
            <TanStackProviders>
              <SystemAlertBanner /> {/* Banner rendered before app content */}
              {children}
              <Toaster
                position="top-center"
                toastOptions={{ className: "mt-[8vh]" }}
                richColors
              />
            </TanStackProviders>
          </ProfileProvider>
        </MSALProvider>
      </body>
    </html>
  );
}