import "reflect-metadata";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { headers } from "next/headers";
import Script from "next/script";

import "./globals.css";
import { ProfileProvider } from "@presentation/components/profileContext/ProfileContext";
import { TanStackProviders } from "./tanstack-provider";
import { MSALProvider } from "./(presentation)/components/auth/MSALAuthProvider";
import 'mapbox-gl/dist/mapbox-gl.css';
import { Toaster } from "@/components/ui/sonner";
import ClarityProvider from './clarityProvider';
import SystemAlertBanner from "./(presentation)/components/SystemAlertBanner";
import FormBricks from './formBricks';

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DAISY",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const allHeaders = await headers();
  const nonce = allHeaders.get("x-nonce") ?? "";

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/images/daisy.png" sizes="any" />
        <Script id="init" nonce={nonce} strategy="afterInteractive">
          {`console.log("Nonce is attached securely!")`}
        </Script>
      </head>
      <body className={`${geistSans.variable} antialiased`}>
        <ClarityProvider />
        <FormBricks />
        <MSALProvider>
          <ProfileProvider>
            <TanStackProviders>
              <SystemAlertBanner /> {/* Banner rendered before app content */}
              {children}
              <Toaster
                position="top-center"
                toastOptions={{ className: "mt-[8vh]" }}
                richColors
              />
            </TanStackProviders>
          </ProfileProvider>
        </MSALProvider>
      </body>
    </html>
  );
}